networks:
  proxy:
    external: true

services:
  angular-21-jwt-auth:
    image: uportal/angular-21-jwt-auth:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.demo-initial.rule=Host(`angular-21-jwt-auth.united-portal.com`)'
      - 'traefik.http.routers.tdemo-initial.tls=true'
      - 'traefik.http.routers.demo-initial.tls.certresolver=lets-encrypt'
      - 'traefik.http.routers.demo-initial.entrypoints=websecure'
      - 'traefik.http.services.demo-initial.loadbalancer.server.port=80'
    restart: unless-stopped
    ports:
      - 4001:80
    networks:
      - proxy

    environment:
      API_BASE_PATH: https://demo-initial-h2.united-portal.com
